### ISSUE TITLE
Update Model Selection Interface

### ISSUE THREAD

**Issue by floridaman** [huggingface/Huggy#1]
Currently it seems impossible to select your training model. Whenever I click the dropdown the game freezes for a few seconds and then advances to the next name in the list. I assume this is because the list of students and subsequently the number of submitted models keeps growing as people start this course.

Any thoughts on uploading the source code for this Unity project? I am happy to take a look at updating the UI/service that is making this request.

**Comment by floridaman** [comment]
On a hunch I unplugged my flight sim hardware and it worked as intended. I'll make a pull request to add a note to the workbook so that other students will be aware of this potential conflict.

**Comment by simoninithomas** [comment]
Thanks we merged your PR I'm closing this issue 🤗
